### PR TITLE
Public Repo Checklist

### PR DESCRIPTION
**Pull request by djanderson**
This repository has met the following criteria necessary for public release: 

- [x] The project, including the test criteria, meets the requirements defined in the ITS Software
Development Publication Policy for making a repository public. The major pre-established
criteria for publication are listed below, and the check mark next to each attests that the
criterion has been met.
  - [X] Demonstrate LTE downlink detection over IQ file
  - [x] Demonstrate LTE downlink detection over the air using RTL-SDR
- [X] Any test data necessary for the code to function is included in the GitHub repository
- [X] The README.md file is complete
- [X] The project complies with the ITS Code Style Guide or an appropriate style guide as agreed to by the sponsor, project lead, or Supervising Division Chief
- [x] Approved disclaimer and licensing language has been included

### CODE REVIEW

**Comment by djanderson** [comment]
I believe that after changing the LICENSE to meet our current approved text, this repository meets all requirements to be made public.

@MichaelCotton, please review.

**Comment by MichaelCotton** [comment]
Do we still want to make this repo public given that we retired msod? Are there msod dependencies or can gr-ltetrigger standalone?

**Comment by djanderson** [comment]
It's completely standalone.

**Review by MichaelCotton — APPROVED** [review]
Useful and adequately documented code base w potential for outside open source collaboration. Mike Cotton (NTIA/ITS Spectrum Monitoring Project Leader)

**Pull request merged**
